import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
import { ModeToggle } from "@/components/ui/toggle-theme";
import ProvidersWrapper from "@/store/providers-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProvidersWrapper>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <body>{children}</body>
        </ThemeProvider>
      </ProvidersWrapper>
    </html>
  );
}
